apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: peeringservers.luxor.io
spec:
  group: luxor.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - replicas
                - pingInterval
              properties:
                replicas:
                  type: integer
                  minimum: 1
                  maximum: 100
                  description: Number of peering server pods to create
                pingInterval:
                  type: integer
                  minimum: 1000
                  description: Interval in milliseconds between pings
                port:
                  type: integer
                  minimum: 1024
                  maximum: 65535
                  default: 8080
                  description: Port for the HTTP server
                image:
                  type: string
                  default: "peering-server:latest"
                  description: Docker image for the peering server
                resources:
                  type: object
                  properties:
                    requests:
                      type: object
                      properties:
                        cpu:
                          type: string
                          default: "100m"
                        memory:
                          type: string
                          default: "128Mi"
                    limits:
                      type: object
                      properties:
                        cpu:
                          type: string
                          default: "200m"
                        memory:
                          type: string
                          default: "256Mi"
            status:
              type: object
              properties:
                replicas:
                  type: integer
                readyReplicas:
                  type: integer
                phase:
                  type: string
                  enum:
                    - Pending
                    - Running
                    - Failed
                lastUpdated:
                  type: string
                  format: date-time
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Replicas
          type: integer
          jsonPath: .spec.replicas
        - name: Ready
          type: integer
          jsonPath: .status.readyReplicas
        - name: Phase
          type: string
          jsonPath: .status.phase
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: peeringservers
    singular: peeringserver
    kind: PeeringServer
    shortNames:
      - ps
      - peer
