---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: peering-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: peering-operator
rules:
  # PeeringServer CRD permissions
  - apiGroups:
      - luxor.io
    resources:
      - peeringservers
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - luxor.io
    resources:
      - peeringservers/status
    verbs:
      - get
      - update
      - patch
  # ConfigMap permissions
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  # Service permissions
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  # StatefulSet permissions
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  # Pod permissions (for status)
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: peering-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: peering-operator
subjects:
  - kind: ServiceAccount
    name: peering-operator
    namespace: default
