apiVersion: apps/v1
kind: Deployment
metadata:
  name: peering-operator
  namespace: default
  labels:
    app: peering-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peering-operator
  template:
    metadata:
      labels:
        app: peering-operator
    spec:
      serviceAccountName: peering-operator
      # BONUS: Security context for pod
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: operator
          image: peering-operator:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              value: "default"
            - name: LOG_LEVEL
              value: "info"
            - name: NODE_OPTIONS
              value: "--max-old-space-size=1536"
          # BONUS: Resource requests and limits for Guaranteed QoS
          resources:
            requests:
              cpu: "100m"
              memory: "1Gi"
            limits:
              cpu: "500m"
              memory: "2Gi"
          # BONUS: Security context for container
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1001
            capabilities:
              drop:
                - ALL
